services:
  docs:
    image: todo_local_docs
    container_name: todo_local_docs
    build:
      context: ./backend
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./backend/.envs/.local/.django
    volumes:
      - /app/.venv
      - ./backend/docs:/docs:z
      - ./backend/config:/app/config:z
      - ./backend/todo:/app/todo:z
    ports:
      - '9000:9000'
    command: /start-docs
